### PR TITLE
feat: Introduce `compress_fits` option in `pipeline_quick` function f…

### PR DESCRIPTION
**Pull request by sageyu123**
…or multi-frequency FITS compression

feat: Introduce `compress_fits` option in `pipeline_quick` function for multi-frequency FITS compression

This update adds a new `compress_fits` keyword to the `pipeline_quick` function, enabling users to toggle the compression of multiple frequency FITS files. This feature can greatly reduce the data size of the output fits files.

### CODE REVIEW

**Comment by surajit4444mondal** [comment]
Sijie, Will the compression also work if we would like to compress the images at multiple times when using fast visibilties? If not, I believe it makes sense to add that functionality in ndfits. What do you think?

**Comment by binchensun** [comment]
Didn’t realize you have already made it that easy!

**Review by binchensun — APPROVED** [review]

**Comment by binchensun** [comment]
There was an issue - the fits files were supposed to have 4 dimensions (npol, nf, ny, nx), while your docompress can only support 3 dimensions. I had to roll it back for the codes to work. Any thoughts?

**Comment by sageyu123** [comment]
The current implementation of docompress indeed removes axes of length one.

I can update the ndfits.wrap function with an option to disable the axis-squeezing behavior. Would it be helpful if we added a parameter, such as squeeze=False, to control this behavior? This way, you can choose to retain all dimensions in the compressed FITS files when necessary. @binchensun

**Comment by binchensun** [comment]
Yes, that would be very helpful! Although we are only doing Stokes I at the
moment, we definitely would like to add Stokes V to the imaging products.

**Comment by sageyu123** [comment]
> Sijie, Will the compression also work if we would like to compress the images at multiple times when using fast visibilties? If not, I believe it makes sense to add that functionality in ndfits. What do you think?

@surajit4444mondal  I'd like to ensure I fully understand your requirements. When you mention the idea of compressing images at multiple times while using fast visibilities, are you referring to the process of compressing a series of 4D image cubes taken at different time intervals into a single FITS file?

**Comment by binchensun** [comment]
I think this is a bigger issue up for discussion. Do we really want the
time axis in individual FITS files? In this case, each FITS file will
become 5D, not the current 4D. A single file will be massive if one tries
to store a long timeseries there, and FITS is really not made for this. I
am inclined to stick with the current scheme that each FITS file is for one
timeframe with four axes: solar x, solar y, frequency, and polarization.

**Comment by sageyu123** [comment]
I like to keep the image cube 4D as well.

**Pull request merged**
