### PR TITLE
Re-organize run_wsclean

### PR DESCRIPTION
**Pull request by peijin94**
Put all wsclean parameters in kwargs, and maintain a default list.

Noted: 
* for wsclean args (e.g. '-minuv-l') need to remove the leading '-', and replace the rest '-' with '_'. (e.g. '-minuv-l' became 'minuv_l')
* The args without value is set to True or False, for example.
* add False to a key to remove it from the args list.

Default list:

```python
    default_kwargs={
        'j':'4',                    # number of threads
        'size':'4096 4096',         # image size
        'scale':'2arcmin',          # pixel scale
        'weight':'uniform',         # weighting scheme
        'no_dirty':'',              # don't save dirty image
        'no_update_model_required':'', # don't update model required
        'no_negative':'',           # no negative gain for CLEAN
        'niter':'10000',            # number of iterations
        'mgain':'0.8',              # maximum gain in each cycle
        'auto_threshold':'3',       # auto threshold
        'auto_mask':'8',            # auto mask
        'pol':'I',                  # polarization
        'minuv_l':'10',             # minimum uv distance in lambda
        'intervals_out':'1',        # number of output images
        'no_reorder':'',            # don't reorder the channels
        'beam_fitting_size':'2',    # beam fitting size
    }
```

For example:
```python
deconvolve.run_wsclean('sun.ms', imagename='output', niter=1000, size='5000 5000'
                       mgain=0.9, auto_mask=False, auto_threshold=False, pol='I')
        
```
creates 
```bash
wsclean  -j 4  -size 5000 5000  -scale 2arcmin  -weight uniform  \
    -no-dirty  -no-update-model-required  -no-negative  \
    -niter 1000  -mgain 0.8  -auto-threshold 3  -auto-mask 5  -pol I  \
    -minuv-l 0  -intervals-out 1  -no-reorder  -beam-fitting-size 2  -field all \
    -name output sun.ms

```

### CODE REVIEW

**Review by binchensun — COMMENTED** [review]
Looks like a reverse process of argparse (https://docs.python.org/3/library/argparse.html)... At quick glance, I think it works. Tagging @surajit4444mondal to comment.

**Review by surajit4444mondal — COMMENTED** [review]
The changes you made look great and is exactly what we envisaged.. But it is not clear to me what is the need of cook_wsclean_cmd. Also, my personal opinion is that, we should only put optional parameters inside kwargs. Imsize and cellsize are not optional parameters and equally important as MSname and imagename. Hence my opinion is that we bring imsize and cell size out as separate parameters..

Also, earlier predict was set to True by default. Now your default kwargs does not have predict as an argument. But when you are calling run_wsclean (for example line 58 of selfcal.py), it is not clear to me how the prediction is happenning. Additionally, can you please confirm that the get_tested.py has run successfully?

**Comment by peijin94** [comment]
cook_wsclean_cmd will be removed, I will put the function (determine pixel size (scale) according to frequency and longest baseline)  inside run_wsclean, by adding args: `auto_scale=False, auto_scale_FOV=fov, telescope_size=3200`.
This is for later speed optimization, using smaller N_pix for lower frequency.

I think we should move `predict` out of kwarg indeed, kwarg should be only for the additional parameters for wsclean.

OK, I will move image size and cell size into the main option, one question is should we keep consistent with wsclean input `size` and `scale` or use `imsize` and `cell`

I modified every run_wsclean function call in the package, but only tested image_ms_quick,
will modify and run more test.

**Comment by surajit4444mondal** [comment]
I think it is better to use size and scale... my motivation for those names were to keep them consistent with CASA.

**Comment by surajit4444mondal** [comment]
This is a big improvement !!!

**Comment by surajit4444mondal** [comment]
Peijin, I looked at your code of the deconvolve.run_wsclean, and based on that I have a few suggestions..
1. Instead of doing size=FOV/pixel scale, choose a number which is can be represented by power of 2,3,5,7,11 and 13. This is because FFTW which is being used, which is fast for these powers. Also note that it is preferable that the sum of powers of 11 and 13 is either 0 or 1. (you can see https://www.fftw.org/fftw3_doc/Real_002ddata-DFTs.html for details)
2. Also I generally set the pix_scale_factor to 3 to ensure slightly higher than Nyquist sampling. However, WSClean will by default do the inversion at Nyquist sampling and then upscale image to requested image size. May I request you to take a look at the image quality in some detail with regard to this parameter?

**Comment by peijin94** [comment]
sure, good point on the size, will add a feature for it to find the cloest suitable number for the clean.

The image quality refers to the final image or the middle step all sky image?

**Comment by surajit4444mondal** [comment]
I think we can just see the all-sky image and compare the calibration solutions generated from it..

**Comment by binchensun** [comment]
Nice!

**Comment by surajit4444mondal** [comment]
The changes look good..

**Pull request merged**
