### PR TITLE
add function to generate calibrations in realtime pipeline

### PR DESCRIPTION
**Pull request by binchensun**
Two new functions added in solar_realtime_pipeline.py.
- download_calibms() is to download all calibration files using an input time. Also do auto-correlation-based flagging (default to True). This can be used to assess the quality of the calibration file. 
- gen_caltables() is to take the downloaded and flagged ms and do bandpass calibration. Also perform flagging of all outrigger antennas to prepare for beamforming calibration tables.

Example usage:
`import solar_realtime_pipeline as realtime`
`ms_calib = realtime.download_calibms('2024-02-10T14:05:30')`
`bcaltbs, bcaltbs_bm = realtime.gen_caltables(ms_calib)`

Default working directory is /lustre/bin.chen/realtime_pipeline/ms_calib/, and output calibration tables are in /lustre/bin.chen/realtime_pipeline/caltables/. One can change them using keywords "download_fold" and "caltable_fold," respectively.

### CODE REVIEW

**Comment by surajit4444mondal** [comment]
The changes look good to me. A minor typo can be fixed.

I think _doflag_ is not used anywhere in _gen_caltables_..  _make_beam_cal_ is used and it is a toggle to flag outliers..

My opinion is to change _make_beam_cal_ to flag_outliers to make the meaning more apparent.

**Comment by dgary50** [comment]
The beam calfiles with .bcal_bm must be renamed to .bcal and moved to /opt/devel/dgary/solar_cal.  A script could do this, but it might be easier to write the beam files into a different folder without changing the extension, so that renaming is not needed.

**Comment by binchensun** [comment]
Thank you, @surajit4444mondal and @dgary50! I have made the changes you recommended. Now calibration tables for beamforming have the same name but are stored in a different directory default to /lustre/bin.chen/realtime_pipeline/caltables_beam/

**Comment by surajit4444mondal** [comment]
looks good.

**Pull request merged**
