### PR TITLE
Add feature: fast vis, uv fit model

### PR DESCRIPTION
**Pull request by peijin94**
Tested speed on calim single node: 4.5s for 12ch * 100time_slot (single subband, 10s)

ovrolwasolar/uv_sourcemodel

### CODE REVIEW

**Comment by surajit4444mondal** [comment]
@peijin94 The changes look good.. I would like to request one change for better readability.

1. In function func_phase_sin, can we replace (u0,v0) as (l0,m0)?

Also, is there any advantage of using the mean of frequencies rather than using the true frequencies inside the loop over channels? 

Also your implemenation of the taper function makes sense. But it is not clear to me why you chose the default value of 0.3. Because I think it just implies that you are tapering the uv-distribution at 0.3lambda, isn't that correct? If this interpretation is correct, even 1 lambda looks very small.

**Comment by peijin94** [comment]
> @peijin94 The changes look good.. I would like to request one change for better readability.
> 
> 1. In function func_phase_sin, can we replace (u0,v0) as (l0,m0)?
> 
> Also, is there any advantage of using the mean of frequencies rather than using the true frequencies inside the loop over channels?
> 
> Also your implemenation of the taper function makes sense. But it is not clear to me why you chose the default value of 0.3. Because I think it just implies that you are tapering the uv-distribution at 0.3lambda, isn't that correct? If this interpretation is correct, even 1 lambda looks very small.

Rrename is reasonable and can be done,
freq-wavelen per channel is a good idea, thanks

The taper is on 0.3*max(uv_dist), attached is the weighting uv scattering plot:
image

0.3 is tested

0.5 fails on some of the frames, 0.3 is a relatively robust one in which case more cases can get a successful fit.

**Comment by surajit4444mondal** [comment]
Ah..  I missed the normalisation part..  This makes perfect sense.. Thanks Peijin for the explanation..

**Comment by peijin94** [comment]
@binchensun could you review this modification and merge to main?

**Review by binchensun — APPROVED** [review]

**Pull request merged**
